ALTER TABLE livro
ADD id_autor INT NOT NULL,
ADD id_categoria INT NOT NULL,
ADD id_editora INT NOT NULL,
ADD id_usuario INT NOT NULL,
ADD data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
ADD FOREIGN KEY (id_autor) REFERENCES autor(id_autor) ON DELETE RESTRICT,
ADD FOREIGN KEY (id_editora) REFERENCES editora(id_editora) ON DELETE RESTRICT,
ADD FOREIGN KEY (id_categoria) REFERENCES categoria(id_categoria) ON DELETE RESTRICT,
ADD FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario) ON DELETE CASCADE;